name: Fetch Packages

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering
  # Webhook
  repository_dispatch:
    types:
      - webhook

jobs:
  fetch-devices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'  # Use the latest Node.js LTS version

      - name: Install dependencies
        run: npm install

      - name: Run fetch-devices script
        env:
          PINGDIR_API: ${{ secrets.PINGDIR_API }}
        run: node _scripts/fetch-packages.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./_src/_data/packages.json

          # Check if there are any changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          
          git commit -m 'Update packages data'
          git push
